[package]
name = "leggo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A SQL query builder for Rust."
categories = []
homepage = "https://github.com/zacharygolba/leggo"
repository = "https://github.com/zacharygolba/leggo"

[dependencies]
